### ISSUE TITLE
definition of "unread count" in push gateway API does not match reality

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-spec#644]

**Comment by ara4n** [comment]
this just caused much confusion with the EX team (cc @stefanceriu).  EX should not be using the badge count from sygnal any more... except it does, and it fights against the locally calculated badge count, and chaos happens: https://github.com/vector-im/element-x-ios/issues/2066. So:

a) the spec should be fixed to describe what the count actually means
b) clients need a way to opt out of it being set on them.

**Comment by richvdh** [comment]
Since this issue was last updated:

* https://github.com/matrix-org/matrix-spec-proposals/pull/4076 has been written as a proposal to allow clients to opt-out of receiving a badge count
* https://github.com/element-hq/synapse/pull/16756 attempted to optimise the code, but that was reverted in https://github.com/element-hq/synapse/pull/16979.

The spec still doesn't match what Synapse does. We still don't have a way for clients to opt out of receiving a badge count.
